const pageCode = {
  DISCOVER: 'DISCOVER',
  DETAIL: 'DETAIL',
  ERROR: 'ERROR',
  SUBSCRIBE: 'SUBSCRIBE',
  RECOMMEND: 'RECOMMEND',
  COLLECTION: 'COLLECTION',
  FOLLOW: 'FOLLOW',
  MESSAGE: 'MESSAGE',
  REWARD: 'REWARD',
  CENTER: 'CENTER',
  HISTORY: 'HISTORY',
  ACCOUNT: 'ACCOUNT',
  PROMOTE: 'PROMOTE',
};
export default pageCode;
